---

- name: Add hiden git repository as PyPI dependency via Pixi
  ansible.builtin.command:
    cmd: >-
      {{ pixi_executable_path }} add --pypi
      'hiden @ git+https://github.com/NSLS2/hiden.git@{{ hiden_git_revision }}'
    chdir: "{{ iocs_directory }}/{{ ioc_name }}"
  changed_when: true

- name: Install dependencies
  ansible.builtin.command:
    cmd: "{{ pixi_executable_path }} install"
    chdir: "{{ iocs_directory }}/{{ ioc_name }}"
  changed_when: true

- name: Install startup script
  ansible.builtin.template:
    src: "templates/st.cmd.j2"
    dest: "{{ iocs_directory }}/{{ ioc_name }}/st.cmd"
    owner: "{{ softioc_user }}"
    group: "{{ softioc_group }}"
    mode: "0775"
