namespace: nsls2
name: ioc_deploy
version: 0.0.1
readme: README.md
authors:
  - your name <example@domain.com>
description: your collection description
license:
  - BSD-3-Clause
license_file: "LICENSE"
tags: []
dependencies: {}
repository: http://github.com/nsls2/nsls2.ioc_deploy
documentation: http://github.com/nsls2/nsls2.ioc_deploy
issues: https://github.com/NSLS2/nsls2.ioc_deploy/issues
build_ignore: []
