---

afg3011:
  type: tektronix_afg3k
  environment:
    P: "XF:31ID1-ES"
    R: "{Tektronix-AFG3K:01}"
    DEVICE_IP: "192.168.1.1"
    PORT: "AFG3K"

  substitutions:
    afg3k:
      - filepath: "$(TOP)/db/TektronixAFG3K.template"
        pattern: ["P", "R", "PORT"]
        instances:
          - ["$(P)", "$(R)", "$(PORT)"]

    asynRecord:
      - filepath: "$(ASYN)/db/asynRecord.db"
        pattern: ["P", "R", "PORT", "ADDR", "TIMEOUT", "OMAX", "IMAX"]
        instances:
          - ["$(P)", "$(R)AsynIO", "$(PORT)", "0", "1", "0", "0"]
