---

advimba_R1_5:
  name: advimba_R1_5
  url: https://github.com/areaDetector/ADVimba
  version: R1-5
  epics_deps:
    EPICS_BASE: /usr/lib/epics
    ASYN: /usr/lib/epics
    AUTOSAVE: /usr/lib/epics
    BUSY: /usr/lib/epics
    CALC: /usr/lib/epics
    DEVIOCSTATS: /usr/lib/epics
    SSCAN: /usr/lib/epics
    SNCSEQ: /usr/lib/epics
    RECCASTER: /usr/lib/epics
  pkg_deps:
    - epics-bundle
  include_base_ad_config: true
  module_deps:
    - adgenicam_R1_10
