---
deploy_ioc_use_common: false
deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adaxis_8c5a423
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/axisIOC"
deploy_ioc_device_specific_env:
  PORT: "AXIS1"
  QSIZE: 20
  XSIZE: 4096
  YSIZE: 4096
  NCHANS: 2048
  CBUFFS: 500
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db:$(ADAXIS)/db"
