---

mcs2-01:
  type: mcs
  model: 2
  environment:
    PORT: "MCS2"
    CTRL_NAME: "MCS2:01"
    CTRL_IP: "127.0.0.1"
    P: "XF31ID1-ES"
    R: "{$(CTRL_NAME)}"
    AXES_MASK: 0xF48
    ENGINEER: C. Engineer

  # Define the individal motor axes here
  axes:
    - name: "X"
      num: 1
      desc: "X"
      mres: 0.00001
      egu: "mm"
      dir: "Pos"
      velo: 2.0

  substitutions:
    asynComm:
      - filepath: "$(ASYN)/db/asynRecord.db"
        pattern: ["P", "R", "ADDR", "PORT", "TIMEOUT", "IMAX", "OMAX"]
        instances:
          - ["$(P)", "$(R)AsynIO", "$(PORT)", "1", "0", "256", "256"]
