---

ADGenICam_R1_10:
  name: ADGenICam_R1_10
  url: https://github.com/areaDetector/ADGenICam
  version: R1-10
  epics_deps:
    EPICS_BASE: /usr/lib/epics
    ASYN: /usr/lib/epics
    AUTOSAVE: /usr/lib/epics
    BUSY: /usr/lib/epics
    CALC: /usr/lib/epics
    DEVIOCSTATS: /usr/lib/epics
    SSCAN: /usr/lib/epics
    SNCSEQ: /usr/lib/epics
  pkg_deps:
    - epics-bundle
    - aravis
    - python3.11 # Required for auto-generating database and bobfiles
  include_base_ad_config: true
  module_deps:
    - ADCore_R3_13
