---


- name: Copy base.cmd
  ansible.builtin.template:
    src: "templates/base.cmd.j2"
    dest: "{{ iocs_directory }}/{{ ioc_name }}/iocBoot/base.cmd"
    owner: "{{ softioc_user }}"
    group: "{{ softioc_group }}"
    mode: "0664"

- name: Copy autosave req file
  ansible.builtin.copy:
    src: "files/auto_settings.req"
    dest: "{{ iocs_directory }}/{{ ioc_name }}/autosave/req/auto_settings.req"
    owner: "{{ softioc_user }}"
    group: "{{ softioc_group }}"
    mode: "0664"
