---

- name: Parse host configuration information
  ansible.builtin.include_role:
    name: nsls2.ioc_deploy.host_info

- name: Deploy netsetup file
  ansible.builtin.template:
    src: "templates/netsetup.j2"
    dest: "{{ deploy_common_common_dir }}/{{ host_info_hostname }}-netsetup.cmd"
    owner: "{{ host_info_softioc_user }}"
    group: "{{ host_info_softioc_group }}"
    mode: "0664"
