---

name: Lint Code Base
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run_superlinter:
    name: Run super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run super linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_NATURAL_LANGUAGE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: false
          VALIDATE_JSCPD: false

  get_changed_files:
    name: Get changed yaml files
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1 # yamllint disable-line rule:line-length
        with:
          files: |
            **/*.{yml,yaml}

  run_ansible_lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest
    needs: [get_changed_files]
    if: needs.get_changed_files.outputs.any_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.14.1 ansible-lint

      - name: Install ansible galaxy requirements
        run: |
          ansible-galaxy install -r collections/requirements.yml --timeout 120

      - name: Lint playbook
        run: |
          ansible-lint -c .ansible-lint --offline \
            ${NEEDS_GET_CHANGED_FILES_OUTPUTS_ALL_CHANGED_FILES}
        env:
          NEEDS_GET_CHANGED_FILES_OUTPUTS_ALL_CHANGED_FILES: ${{ needs.get_changed_files.outputs.all_changed_files }} # yamllint disable-line rule:line-length
